# Site wide configuration

title: Write Less. For More.
locale: en_US
description: Blog on all things technical writing and maybe other random stuff
logo: site-logo.png
search: true
url: http://localhost:4000

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Kenneth Lau
  avatar: bio-photo.jpg
  email: kennethcklau@gmail.com
  disqus-shortname:
  twitter: KennyLau19
  facebook: #kenny.lau.10004
  github: kenneth-lau
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: kenneth-lau19
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
